[build]
  publish = "public/"
  command = "npm run build"

[build.processing]
  skip_processing = false # Ensures processing is enabled
  css = { bundle = true, minify = true }
  js = { bundle = true, minify = true }
  html = { pretty_urls = true }
  images = { compress = true }

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [
    "public/assets/images",
    ".cache"
  ]

# HTTP redirects - these should be processed first
[[redirects]]
  from = "http://peak-pressurewash.com/*"
  to = "https://peakhomeimprovement.us/:splat"
  status = 301
  force = true
  conditions = {Scheme = ["http"]}

[[redirects]]
  from = "http://www.peak-pressurewash.com/*"
  to = "https://peakhomeimprovement.us/:splat"
  status = 301
  force = true
  conditions = {Scheme = ["http"]}

# HTTPS redirects
[[redirects]]
  from = "https://peak-pressurewash.com/*"
  to = "https://peakhomeimprovement.us/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.peak-pressurewash.com/*"
  to = "https://peakhomeimprovement.us/:splat"
  status = 301
  force = true